### ISSUE TITLE
testing amazon s3 uploads

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#260]
I am having trouble testing an upload to s3: 

```
tape('/orgs/{id}/edit (POST) - admin adds an image to the edit org form', t => {
  var addLogo = {
    method: 'POST',
    url: '/orgs/0/edit',
    payload: {
      name: 'Apple',
      mission_statement: 'Change the economy',
      logo: fs.readFileSync(__dirname + '/../helpers/generic.jpg'),
      file_name: 'generic.jpg'
    },
    headers: { cookie: `token=${admin_token}`}
  }

  server.inject(addLogo, res => {
    t.equal(res.statusCode, 200, 'status code is 200 if logo is present');
    t.end();
  });
});
```

--> the payload comes through as:

```
request.payload:  { 
  name: 'Apple',
  mission_statement: 'Change the economy',
  logo:
   { type: 'Buffer',
     data:
      [ 255,
        216,
        255,
        224,
        0,
        16,
        74,
        70,
        73,
        70,
        ... 9757 more items ] },
  file_name: 'generic.jpg' }
```

And this is my error message:

```
Error: Unsupported body payload object
    at ManagedUpload.self.fillQueue (/Users/jackmurphy/web/ce100-app/node_modules/aws-sdk/lib/s3/managed_upload.js:83:21)
    at ManagedUpload.AWS.S3.ManagedUpload.AWS.util.inherit.send (/Users/jackmurphy/web/ce100-app/node_modules/aws-sdk/lib/s3/managed_upload.js:180:33)
    at upload (/Users/jackmurphy/web/ce100-app/node_modules/aws-sdk/lib/services/s3.js:829:50)
    at Object.upload (/Users/jackmurphy/web/ce100-app/server/s3.js:22:12)
    at module.exports (/Users/jackmurphy/web/ce100-app/server/handlers/edit-org.js:11:6)
    at Object.internals.handler (/Users/jackmurphy/web/ce100-app/node_modules/hapi/lib/handler.js:96:36)
    at request._protect.run (/Users/jackmurphy/web/ce100-app/node_modules/hapi/lib/handler.js:30:23)
    at internals.Protect.run (/Users/jackmurphy/web/ce100-app/node_modules/hapi/lib/protect.js:62:12)
    at exports.execute (/Users/jackmurphy/web/ce100-app/node_modules/hapi/lib/handler.js:24:22)
    at each (/Users/jackmurphy/web/ce100-app/node_modules/hapi/lib/request.js:380:16)
```

When going through the flow on my local branch i get this as a payload: 

```
request.payload:  { name: 'Apple',
  mission_statement: 'Change the economy',
  file_name: 'images.png',
  logo: <Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 00 d2 00 00 00 f0 08 03 00 00 00 42 23 ca 4d 00 00 00 3c 50 4c 54 45 ff ff ff b5 b5 b5 b2 b2 b2 ... > }
```

Any advice on how i can make my logo buffer in my test in the same form as the one in the actual form?

**Comment by mk4111** [comment]
hmm... so the Buffer is coming through as a Buffer 'object' instead of the ```<Buffer >``` format right? I'm not entirely sure what the difference is, or what either formats are actually called but I'm thinking that the ```<Buffer ...?``` format got JSON.stringify-d by the form or JSON.parse-d by Hapi when sending to the backend. Although it works locally so maybe not the case.

Can you send the image as a utf8 or base64 img and convert it to a Buffer on the backend, then send it up?

**Comment by nelsonic** [comment]
@jackcarlisle please assist. thanks!

**Comment by JMurphyWeb** [comment]
@nelsonic just caught up with @jackcarlisle. He wasn't sure as he used night-watch.

**Comment by nelsonic** [comment]
@JMurphyWeb please let me know what git branch this is on so I can run it locally and help you debug it.

**Comment by JMurphyWeb** [comment]
https://github.com/emfoundation/ce100-app/tree/add-logo

**Comment by JMurphyWeb** [comment]
I am sorry but I don't think I updated the shared doc file with the additions to .env. It is a small change, the major change should be made in the computers root directory which i did update in the shared doc.

**Comment by JMurphyWeb** [comment]
I think we need to add the AWS region to the .env which is the same as the existing AWS region but just has a different key name.
