### ISSUE TITLE
Send email error

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#572]
Getting the following error from aws when trying to create a new user and sending them the activation email:

```

SES ERROR: { AccessDenied: User `arn:aws:iam::796463698701:user/ce100-s3upload' is not authorized to perform `ses:SendEmail' on resource `arn:aws:ses:eu-west-1:796463698701:identity/ce100.emf@gmail.com'
    at Request.extractError (/Users/jmurphy/web/ce100-app/node_modules/aws-sdk/lib/protocol/query.js:40:29)
    at Request.callListeners (/Users/jmurphy/web/ce100-app/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/jmurphy/web/ce100-app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/jmurphy/web/ce100-app/node_modules/aws-sdk/lib/request.js:668:14)
    at Request.transition (/Users/jmurphy/web/ce100-app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/jmurphy/web/ce100-app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/jmurphy/web/ce100-app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/jmurphy/web/ce100-app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/jmurphy/web/ce100-app/node_modules/aws-sdk/lib/request.js:670:12)
    at Request.callListeners (/Users/jmurphy/web/ce100-app/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'User `arn:aws:iam::796463698701:user/ce100-s3upload\' is not authorized to perform `ses:SendEmail\' on resource `arn:aws:ses:eu-west-1:796463698701:identity/ce100.emf@gmail.com\'',
  code: 'AccessDenied',
  time: 2017-01-13T11:07:40.325Z,
  requestId: '7f9b3d13-d980-11e6-859b-011fa23692e3',
  statusCode: 403,
  retryable: false,
  retryDelay: 0.22867108224833288 } AccessDenied: User `arn:aws:iam::796463698701:user/ce100-s3upload' is not authorized to perform `ses:SendEmail' on resource `arn:aws:ses:eu-west-1:796463698701:identity/ce100.emf@gmail.com'
    at Request.extractError (/Users/jmurphy/web/ce100-app/node_modules/aws-sdk/lib/protocol/query.js:40:29)
    at Request.callListeners (/Users/jmurphy/web/ce100-app/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/jmurphy/web/ce100-app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/jmurphy/web/ce100-app/node_modules/aws-sdk/lib/request.js:668:14)
    at Request.transition (/Users/jmurphy/web/ce100-app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/jmurphy/web/ce100-app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/jmurphy/web/ce100-app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/jmurphy/web/ce100-app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/jmurphy/web/ce100-app/node_modules/aws-sdk/lib/request.js:670:12)
    at Request.callListeners (/Users/jmurphy/web/ce100-app/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
```

**Comment by JMurphyWeb** [comment]
The new/latest version of sendemail is `2.8.0`

The version on our `package.json` is `2.3.0`

Which suggests that it is not due to the new version.

**Comment by mk4111** [comment]
Yeah - the reason why it's `2.3.0` instead of `^2.3.0` is because the new API breaks our app --> we have to change the way our app interacts with sendemail to fix this I think #540

**Comment by mk4111** [comment]
Are you trying to update the version? Or are you getting this issue, and is that why you're trying to update the version?

**Comment by JMurphyWeb** [comment]
on master. not trying to update version.

**Comment by JMurphyWeb** [comment]
Fix was in the IAM/Users section of the aws console, where we can edit our user account settings and permissions. Our account did not have permission to use sendEmail service, so we just attached the following send email policy to our account: `AmazonSesSendingAccess - Inline policy`

<img width="722" alt="screen shot 2017-01-14 at 08 34 25" src="https://cloud.githubusercontent.com/assets/12638261/21953642/ef557742-da34-11e6-92a3-611230079e71.png">

**Comment by nelsonic** [comment]
@JMurphyWeb thanks for _sharing_ how you updated it. 😍 
hope you're having a good morning. (_don't do work on weekends!_) 😉
